# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
  commit-message:
      prefix: ":seedling:"
  open-pull-requests-limit: 3
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "monthly"
  labels:
    - "ok-to-test"
  commit-message:
      prefix: ":seedling:"
  groups:
    github-actions:
      patterns:
        - "*"
      # These actions directly influence the build process and are excluded from grouped updates
      exclude-patterns:
        - "actions/setup-go"
        - "arduino/setup-protoc"
        - "goreleaser/goreleaser-action"

