apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-global-hub-grafana
  name: multicluster-global-hub-grafana
  namespace: {{.Namespace}}
spec:
  ports:
  - name: oauth-proxy
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: multicluster-global-hub-grafana
  type: ClusterIP