{{ if .EnableKRaft }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{.KafkaCluster}}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
  namespace: {{.Namespace}}
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - authentication:
          type: tls
        configuration:
          bootstrap:
            nodePort: 30095
          brokers:
          - broker: 0
            advertisedHost: {{.KinDClusterIPAddress}}
        name: external
        port: 9095
        tls: true
        type: nodeport
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{ end }}