GRANT USAGE ON SCHEMA spec TO guest;
GRANT USAGE ON SCHEMA status TO guest;
GRANT USAGE ON SCHEMA event TO guest;
GRANT USAGE ON SCHEMA history TO guest;
GRANT USAGE ON SCHEMA local_spec TO guest;
GRANT USAGE ON SCHEMA local_status TO guest;

GRANT SELECT ON ALL TABLES IN SCHEMA spec TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA status TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA event TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA history TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA local_spec TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA local_status TO guest;
