GRANT USAGE ON SCHEMA spec TO guest;
GRANT USAGE ON SCHEMA status TO guest;
GRANT USAGE ON SCHEMA event TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA spec TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA status TO guest;
GRANT SELECT ON ALL TABLES IN SCHEMA event TO guest;