apiVersion: v1
items:
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-100-cluster-round-1","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-100","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-04T04:44:42Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-100-cluster-round-1
    namespace: multicluster-global-hub
    resourceVersion: "10092585"
    uid: 872a886b-2c90-4b43-8fe4-0efd1236d41f
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-100
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-04T04:44:42Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-04T04:44:47Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-04T04:44:52Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-04T04:45:12Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-04T04:47:12Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-04T04:47:17Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-100-cluster-round-2","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-100","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-04T04:49:06Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-100-cluster-round-2
    namespace: multicluster-global-hub
    resourceVersion: "10113906"
    uid: f588ecca-0edf-4287-af45-a424212cb530
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-100
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-04T04:49:06Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-04T04:49:11Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-04T04:49:16Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-04T04:49:36Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-04T04:53:41Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-04T04:53:46Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-100-cluster-round-3","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-100","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-04T04:55:35Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-100-cluster-round-3
    namespace: multicluster-global-hub
    resourceVersion: "10128786"
    uid: b5e95330-d1a1-42bf-b3fc-9fee8e5da98b
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-100
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-04T04:55:35Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-04T04:55:40Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-04T04:55:45Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-04T04:56:05Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-04T04:58:25Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-04T04:58:30Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
kind: List
metadata:
  resourceVersion: ""