apiVersion: v1
items:
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-50-cluster-round-1","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-50","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-03T03:15:54Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-50-cluster-round-1
    namespace: multicluster-global-hub
    resourceVersion: "8394026"
    uid: 9bf589df-7ba9-4254-abfa-a98c67c9c28c
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-50
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-03T03:15:54Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-03T03:15:59Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-03T03:16:04Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-03T03:16:14Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-03T03:17:24Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-03T03:17:29Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-50-cluster-round-2","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-50","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-03T03:19:26Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-50-cluster-round-2
    namespace: multicluster-global-hub
    resourceVersion: "8403207"
    uid: a87ce202-7a44-47dc-a7bb-35e58eba2653
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-50
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-03T03:19:26Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-03T03:19:31Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-03T03:19:36Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-03T03:19:51Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-03T03:20:51Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-03T03:20:56Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-50-cluster-round-3","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-50","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-03T03:22:44Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-50-cluster-round-3
    namespace: multicluster-global-hub
    resourceVersion: "8412358"
    uid: ff4b5077-8ea0-474f-bc5f-0702e55a4157
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-50
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-03T03:22:44Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-03T03:22:49Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-03T03:22:54Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-03T03:23:09Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-03T03:24:19Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-03T03:24:24Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-50-cluster-round-4","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-50","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-03T03:26:57Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-50-cluster-round-4
    namespace: multicluster-global-hub
    resourceVersion: "8421894"
    uid: 0f82ab34-ecbd-4bb1-a4bc-d16a33e54255
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-50
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-03T03:26:57Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-03T03:27:02Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-03T03:27:07Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-03T03:27:17Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-03T03:28:22Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-03T03:28:27Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-50-cluster-round-5","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-50","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-03T03:29:57Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-50-cluster-round-5
    namespace: multicluster-global-hub
    resourceVersion: "8430820"
    uid: 254f43e9-e890-4f61-9a83-8c527d07aa6f
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-50
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-03T03:29:57Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-03T03:30:02Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-03T03:30:07Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-03T03:30:22Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-03T03:31:47Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-03T03:31:52Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-50-cluster-round-6","namespace":"multicluster-global-hub"},"spec":{"from":"local-cluster","includedManagedClustersPlacementRef":"migration-50","supportedConfigs":{"stageTimeout":"60m"},"to":"mh1"}}
    creationTimestamp: "2025-09-03T03:35:03Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-50-cluster-round-6
    namespace: multicluster-global-hub
    resourceVersion: "8440836"
    uid: 3a5181e4-ff1a-4e65-9db9-94815b84ef7b
  spec:
    from: local-cluster
    includedManagedClustersPlacementRef: migration-50
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: mh1
  status:
    conditions:
    - lastTransitionTime: "2025-09-03T03:35:03Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-03T03:35:08Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-03T03:35:13Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-03T03:35:28Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-03T03:36:48Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-03T03:36:53Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
kind: List
metadata:
  resourceVersion: ""