apiVersion: v1
items:
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-100-cluster-round-1-bk","namespace":"multicluster-global-hub"},"spec":{"from":"mh1","includedManagedClustersPlacementRef":"migration-100","supportedConfigs":{"stageTimeout":"60m"},"to":"local-cluster"}}
    creationTimestamp: "2025-09-04T05:30:39Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-100-cluster-round-1-bk
    namespace: multicluster-global-hub
    resourceVersion: "10183683"
    uid: 13ccb260-fdfd-458c-b608-5dee3e5e5410
  spec:
    from: mh1
    includedManagedClustersPlacementRef: migration-100
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: local-cluster
  status:
    conditions:
    - lastTransitionTime: "2025-09-04T05:30:39Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-04T05:30:44Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-04T05:30:54Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-04T05:31:09Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-04T05:32:24Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-04T05:32:44Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-100-cluster-round-2-bk","namespace":"multicluster-global-hub"},"spec":{"from":"mh1","includedManagedClustersPlacementRef":"migration-100","supportedConfigs":{"stageTimeout":"60m"},"to":"local-cluster"}}
    creationTimestamp: "2025-09-04T05:36:08Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-100-cluster-round-2-bk
    namespace: multicluster-global-hub
    resourceVersion: "10215150"
    uid: 2225d152-f9ac-4033-84e4-2809cc621b19
  spec:
    from: mh1
    includedManagedClustersPlacementRef: migration-100
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: local-cluster
  status:
    conditions:
    - lastTransitionTime: "2025-09-04T05:36:08Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-04T05:36:13Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-04T05:36:23Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-04T05:36:38Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-04T05:38:18Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-04T05:38:38Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
- apiVersion: global-hub.open-cluster-management.io/v1alpha1
  kind: ManagedClusterMigration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"global-hub.open-cluster-management.io/v1alpha1","kind":"ManagedClusterMigration","metadata":{"annotations":{},"name":"migrate-100-cluster-round-3-bk","namespace":"multicluster-global-hub"},"spec":{"from":"mh1","includedManagedClustersPlacementRef":"migration-100","supportedConfigs":{"stageTimeout":"60m"},"to":"local-cluster"}}
    creationTimestamp: "2025-09-04T05:42:13Z"
    finalizers:
    - global-hub.open-cluster-management.io/migration-cleanup
    generation: 2
    name: migrate-100-cluster-round-3-bk
    namespace: multicluster-global-hub
    resourceVersion: "10243184"
    uid: 57aa44b9-6576-4824-aa7d-e83c27fbe4a5
  spec:
    from: mh1
    includedManagedClustersPlacementRef: migration-100
    supportedConfigs:
      stageTimeout: 1h0m0s
    to: local-cluster
  status:
    conditions:
    - lastTransitionTime: "2025-09-04T05:42:13Z"
      message: Migration instance is started
      reason: InstanceStarted
      status: "True"
      type: MigrationStarted
    - lastTransitionTime: "2025-09-04T05:42:18Z"
      message: Migration resources have been validated
      reason: ResourceValidated
      status: "True"
      type: ResourceValidated
    - lastTransitionTime: "2025-09-04T05:42:28Z"
      message: All source and target hubs have been successfully initialized
      reason: ResourceInitialized
      status: "True"
      type: ResourceInitialized
    - lastTransitionTime: "2025-09-04T05:42:43Z"
      message: Resources have been successfully deployed to the target hub cluster
      reason: ResourcesDeployed
      status: "True"
      type: ResourceDeployed
    - lastTransitionTime: "2025-09-04T05:43:58Z"
      message: All migrated clusters have been successfully registered
      reason: ClusterRegistered
      status: "True"
      type: ClusterRegistered
    - lastTransitionTime: "2025-09-04T05:44:18Z"
      message: Resources have been successfully cleaned up from the hub clusters
      reason: ResourceCleaned
      status: "True"
      type: ResourceCleaned
    phase: Completed
kind: List
metadata:
  resourceVersion: ""
