apiVersion: apps/v1
kind: Deployment
metadata:
  name: relations-api
  namespace: {{.Namespace}}
  labels:
    app: relations-api
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      app: relations-api
  template:
    metadata:
      labels:
        app: relations-api
    spec:
      containers:
      - name: api
        image: {{.Image}}
        imagePullPolicy: {{.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /api/authz/livez
            port: 8000
        readinessProbe:
          httpGet:
            path: /api/authz/readyz
            port: 8000
        ports:
        - name: http
          containerPort: 8000
        - name: grpc
          containerPort: 9000
        env:
        - name: SPICEDB_PRESHARED
          valueFrom:
            secretKeyRef:
              key: {{.SpiceDBConfigSecretPreSharedKey}}
              name: {{.SpiceDBConfigSecretName}}
        - name: SPICEDB_ENDPOINT
          value: {{.SpiceDBConfigClusterName}}.{{.Namespace}}.svc.cluster.local:50051
        - name: SPICEDB_SCHEMA_FILE
          value: /etc/schema/schema.zed
        volumeMounts:
          - name: schema
            mountPath: /etc/schema
      volumes:
      - name: schema
        configMap:
          name: spicedb-schema
      {{- if .ImagePullSecret }}
      imagePullSecrets:
        - name: {{.ImagePullSecret}}
      {{- end }}
      {{- if .NodeSelector }}
      nodeSelector:
        {{- range $key, $value := .NodeSelector}}
        "{{$key}}": "{{$value}}"
        {{- end}}
      {{- end }}
      {{- if .Tolerations }}
      tolerations:
        {{- range .Tolerations}}
        - key: "{{.Key}}"
          operator: "{{.Operator}}"
          {{- if .Value}}
          value: "{{.Value}}"
          {{- end}}
          effect: "{{.Effect}}"
          {{- if .TolerationSeconds}}
          tolerationSeconds: {{.TolerationSeconds}}
          {{- end}}
        {{- end}}
      {{- end }}