{{- if .InstallHostedMode -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multicluster-global-hub-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - get
  - watch
  - list
{{- end -}}
