{{- if and .InstallHostedMode .KafkaClusterCASecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.KafkaClusterCASecret}}
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
type: Opaque
data:
  "ca.crt": "{{.KafkaClusterCACert}}"
{{- end -}}