# clusterrole for multicluster-global-hub-manager, the change to this file musted be made to
# https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/rbac/aggregated_role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-global-hub:multicluster-global-hub-manager
  labels:
    name: multicluster-global-hub-manager
rules:
# for oauth-proxy
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
# for oauth-proxy
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - "policy.open-cluster-management.io"
  resources:
  - policies
  - policies/status
  - policies/finalizers
  - placementbindings
  - placementbindings/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - "apps.open-cluster-management.io"
  resources:
  - placementrules
  - placementrules/status
  - subscriptionstatuses
  - subscriptionstatuses/status
  - subscriptionreports
  - subscriptionreports/status
  - subscriptions/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "addon.open-cluster-management.io"
  resources:
  - clustermanagementaddons
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - placements
  - placements/finalizers
  - placements/status
  - placementdecisions
  - placementdecisions/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclusterhubs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - events
  - secrets
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - managedclustersets
  - managedclustersets/finalizers
  - managedclustersetbindings
  - managedclustersetbindings/finalizers
  - placements
  - placements/finalizers
  - managedclusters
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "apps.open-cluster-management.io"
  resources:
  - placementrules
  - placementrules/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "apps.open-cluster-management.io"
  resources:
  - subscriptions
  - channels
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "app.k8s.io"
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - "authentication.open-cluster-management.io"
  resources:
  - managedserviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - "global-hub.open-cluster-management.io"
  resources:
  - managedclustermigrations
  - managedclustermigrations/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
