apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  finalizers:
  - strimzi.io/topic-operator
  labels:
    strimzi.io/cluster: kafka
  name: my-topic
spec:
  partitions: 1
  replicas: 1
  config:
    # Retention policy for migration: 10 minutes to align with migration timeout
    cleanup.policy: compact,delete
    retention.ms: 600000  # 10 minutes for migration timeout
    retention.bytes: "1073741824"  # 1GB per partition
