apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: global-hub
  namespace: {{.Namespace}}
  labels:
    cluster.open-cluster-management.io/backup: globalhub
spec:
  agentInstallNamespace: multicluster-global-hub-agent
  customizedVariables:
  - name: enableSyncLabelsToClusterClaims
    value: "false"
