apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: non-local-cluster
  namespace: {{.Namespace}}
spec:
  clusterSets:
  - global
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: local-cluster
          operator: "DoesNotExist"
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
