apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: non-default-cluster
  namespace: {{.Namespace}}
spec:
  clusterSets:
  - global
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
         ### This is the label used to select hosted clusters, could support more kind of clusters in the future
        - key: global-hub.open-cluster-management.io/deploy-mode
          operator: In
          values: ["hosted"]
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
