apiVersion: v1
kind: ServiceAccount
metadata:
  name: multicluster-global-hub-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
