{{- if .InventoryServerCACert -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.InventoryServerCASecret}}
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
type: Opaque
data:
  "ca.crt": "{{.InventoryServerCACert}}"
{{- end -}}