{{ if .ImagePullSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.ImagePullSecretName}}
  namespace: {{.AddonInstallNamespace}}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.ImagePullSecretData}}
{{ end }}