apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicluster-global-hub?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "release-2.12"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: release-globalhub-1-3
    appstudio.openshift.io/component: multicluster-global-hub-agent-globalhub-1-3
    pipelines.appstudio.openshift.io/type: build
  name: multicluster-global-hub-agent-globalhub-1-3-on-pull-request
  namespace: acm-multicluster-glo-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/acm-multicluster-glo-tenant/release-globalhub-1-3/multicluster-global-hub-agent-globalhub-1-3:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: agent/Containerfile.agent
  - name: path-context
    value: .
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/ppc64le
    - linux/s390x
    - linux/arm64
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: '[ {"type": "gomod", "path": "."}, {"type": "rpm", "path": "."} ]'
  - name: use-dev-package-managers
    value: "true"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-multicluster-global-hub-agent-globalhub-1-3
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
