apiVersion: v1
kind: Secret
metadata:
  name: restic-secret
  namespace: open-cluster-management-backup
  labels:
   cluster.open-cluster-management.io/backup: volsync
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:s3.amazonaws.com/<RESTIC_REPO>
  RESTIC_PASSWORD: <RESTIC_PASSWD>
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_ACCESS_KEY_SECRET>
