name: Go

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Setup gci
        run: go install github.com/daixiang0/gci@latest

      - name: Setup gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: format
        run: make strict-fmt
  verify-bundle:
    name: verify bundle
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: bundle
        run: cd operator && make bundle
