name: Go

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Setup gci
        run: go install github.com/daixiang0/gci@latest

      - name: Setup gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: format
        run: make strict-fmt
  verify-bundle:
    name: verify bundle
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: bundle
        run: cd operator && make bundle

  scorecard-test:
    name: bundle scorecard test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Download operator-sdk
        uses: drmendes/setup-k8s-operator-sdk@v1.1.5
        with:
          version: "^1.34.1"
      
      - name: scorecard
        run: cd operator && operator-sdk scorecard ./bundle/
